### ISSUE TITLE
Installation Documentation

### ISSUE THREAD

**Issue by ericbmerritt** [davidben/embedded-emacs#1]
This is great, exactly what I have been looking for for some time. However, I can't seem to find documentation about how to install it. Even the general Chrome NPAPI installation documentation is non-existant. Any chance you can add something to the readme to point the way?

**Comment by davidben** [comment]
I intend to package it up and upload it in the Web Store at some point. Dunno when that'll be; I only poke about this sporadically (and I'm traveling right now, so I can't really work on it). I think there are mostly random focus issues I want to work out. Also Emacs is really buggy; I have a patch for them they need to pick up for `emacsclient -parent-id` to not cause issues, and you need emacs 24 (not yet released) to avoid a resize bug.

Anyway. For now, you'll want to load it as an unpacked extension. Run `scons` to build it. The extension is then in the `chrome` directory. Their development documentation should tell you how to load an unpacked one.

http://code.google.com/chrome/extensions/getstarted.html
